imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

parameters:
    locale: en

framework:
    translator:      ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  ~
    fragments:       ~
    http_method_override: true

twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

swiftmailer:
  spool:     { type: memory }
  transport: smtp
  host:      mailtrap.io
  username:  4934098327f5dd6a8
  password:  adb528f2339154
  auth_mode: cram-md5
  port: 2525

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Bundle\UserBundle\Entity\User
    group:
          group_class: Bundle\UserBundle\Entity\Group
    registration:
            form:
                type: Bundle\UserBundle\Form\Type\UserFormType